matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      language: cpp
      
    - os: linux
      language: cpp
      
    - os: windows
      language: cpp

before_script:
  - mkdir obj
  - cd obj/ && mkdir src
  - cd src/ && mkdir headers
  - cd ../../ && ls

script:
  - g++ -Wall -fexceptions -O2 -I./src/headers -c ./src/main.cpp -o ./obj/src/main.o
  - g++ -Wall -fexceptions -O2 -I./src/headers -c ./src/headers/colors.cpp -o ./obj/src/headers/colors.o
  - g++ -Wall -fexceptions -O2 -I./src/headers -c ./src/headers/config_reader.cpp -o ./obj/src/headers/config_reader.o

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
