# /*****************************************************
# * Copyright (c) 2022 Micorksen.
# * 
# * Use of this source code is governed by an MIT-style
# * license that can be found in the LICENSE file or at
# * https://opensource.org/licenses/MIT.
# * 
# ******************************************************/

# Notifications options.
notifications:
    email:
        recipients:
            - hello@micorksen.xyz
            
        # Change is when the repository status goes from pass to fail or vice versa.
        on_success: change
        on_failure: always

# OS to build.
os:
    - osx
    - linux
    - windows

# Specify language, compiler and script to run.
language: cpp
script:
  - make --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then "make build-apple"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then "make build-linux"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then "make build-windows"; fi

# Configure which branches to run.
branches:
    except: []
#        - development

# Deploy options.
deploy:
    provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN
    file_glob: true
    file:
        - "Set-DNS-Cli"
    on:
        tags: true
