name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  artifact-macos:
    runs-on: macos-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/macos.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-macos"
      - name: Create the artifact URL
        uses: actions/download-artifact@v3
        with:
          name: "Set-DNS-Cli-x64-macos"
          path: .
      - name: Get the artifact URL
        run: echo ${{ steps.download.outputs.download-path }}
        
        
  artifact-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev=3.0.2-0ubuntu1.6  
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-linux"
      - name: Create the artifact URL
        uses: actions/download-artifact@v3
        with:
          name: "Set-DNS-Cli-x64-linux"
          path: .
      - name: Get the artifact URL
        run: echo ${{ steps.download.outputs.download-path }}
      
  artifact-windows:
    runs-on: windows-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/windows.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64.exe"
      - name: Create the artifact URL
        uses: actions/download-artifact@v3
        with:
          name: "Set-DNS-Cli-x64.exe"
          path: .
      - name: Get the artifact URL
        run: echo ${{ steps.download.outputs.download-path }}
