name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Compiling the project
        uses: actions/checkout@v3.0.2
      - run: |
          ls
          g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli
