name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  artifact-macos:
    runs-on: macos-latest
    steps:
      - name: Install the dependencies
        run: "brew install openssl"
      - name: Clone the project
        uses: actions/checkout@v3.0.2
      - name: Compile the project
        run: |
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include
          g++ src/main.cpp src/os/macos.cpp -lssl -lcrypto -static -o Set-DNS-Cli-x64-macos
      - name: Send the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : macos"
          body: |
            Check the attachment to publish the release 😁
            Don't forget to check also 🤞
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64-macos
        
        
  artifact-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the project
        uses: actions/checkout@v3.0.2
      - name: Compile the project
        run: "g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-linux"
      - name: Send the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : ubuntu"
          body: |
            Check the attachment to publish the release 😁
            Don't forget to check also 🤞
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64-linux
      
  artifact-windows:
    runs-on: windows-latest
    steps:
      - name: Install the dependencies
        run: "choco install openssl"
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/windows.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64.exe"
      - name: Sending the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : windows"
          body: |
            Check the attachment to publish the release 😁
            Don't forget to check also 🤞
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64.exe
