name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  artifact-macos:
    runs-on: macos-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/macos.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-macos"
        
  artifact-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-linux"
        
  artifact-windows:
    runs-on: windows-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/windows.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64.exe"
