name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  artifact-macos:
    runs-on: macos-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "/usr/local/bin/g++ src/main.cpp src/os/macos.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-macos"
      - name: Sending the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : macos"
          body: "Check the attachment to publish the release 😁"
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64-macos
        
        
  artifact-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64-linux"
      - name: Sending the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : ubuntu"
          body: "Check the attachment to publish the release 😁"
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64-linux
      
  artifact-windows:
    runs-on: windows-latest
    steps:
      - name: Cloning the project
        uses: actions/checkout@v3.0.2
      - name: Compiling the project
        run: "g++ src/main.cpp src/os/windows.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli-x64.exe"
      - name: Create the artifact URL
        uses: actions/download-artifact@v3
        with:
          name: "Set-DNS-Cli-x64.exe"
          path: .
      - name: Get the artifact URL
        run: echo ${{ steps.download.outputs.download-path }}
      - name: Sending the artifact via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: pelops.o2switch.net
          server_port: 465
          secure: true
          username: no-reply@micorksen.eu
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[Micorksen/Set-DNS-Cli] Run succeeded : windows"
          body: "Check the attachment to publish the release 😁"
          to: hello@micorksen.eu
          from: Matteo C.
          attachments: Set-DNS-Cli-x64.exe
