name: Build the application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: kurocha/setup-cpp@v1
      - run: "g++ src/main.cpp src/os/linux.cpp src/vendor/INIReader/* src/vendor/http/* -lssl -lcrypto -static -o Set-DNS-Cli"
